name: Build Python wheel for Alpine Linux

on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:

  build:
    name: Build Python wheel for Alpine Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Run build script in Alpine container
        run: docker-compose up build
      - name: List build artifacts
        run: ls -hl ${{ github.workspace }}/${{ github.event.repository.name }}/dist
      - name: Show sha256 of build artifacts
        run: shasum -a 256 ${{ github.workspace }}/${{ github.event.repository.name }}/dist/*
      - name: Upload wheel as release asset
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_content_type: application/octet-stream
          asset_path: ${{ github.workspace }}/${{ github.event.repository.name }}/dist/elastic_apm-${{ github.event.release.tag_name }}-py3-none-any.whl
          asset_name: elastic_apm-${{ github.event.release.tag_name }}-py3-none-any.whl
          upload_url: ${{ github.event.release.upload_url }}
